### PR TITLE
Add support for HMAC-SHA256

### PR DESCRIPTION
**Pull request by jrissler**
Thanks for creating this library, it's great!

Is this how you envisioned extending it to support other signing methods? If so, I'd love for it to support SHA-256 :)

### CODE REVIEW

**Comment by jrissler** [comment]
I don't think the CI check is failing because of this change.

**Comment by jrissler** [comment]
@lexmag My bad on delay, should be gtg now :)

**Review by lexmag — APPROVED** [review]

**Comment by lexmag** [comment]
@jrissler thank you. 💛

**Comment by jrissler** [comment]
Awesome thanks @lexmag 😁

**Pull request merged**
