### PR TITLE
Rename Enum.partition/2 to Enum.split_with/2

### PR DESCRIPTION
**Pull request by GusGA**
Enum.partition/2 is deprecated

### CODE REVIEW

**Comment by whatyouhide** [comment]
Hey @GusGA, by doing this you are effectively dropping support for Elixir <= 1.4, so this is not the way to go. What you want to do is likely something similar to what was done in https://github.com/whatyouhide/redix_pubsub/pull/14.

**Comment by GusGA** [comment]
@whatyouhide Great, I will change it.

Thanks.

**Comment by whatyouhide** [comment]
\cc @lexmag

**Comment by lexmag** [comment]
Thank you @GusGA. 💛

**Comment by GusGA** [comment]
Thanks to you @lexmag for allowing me to participate.

**Pull request merged**
